export const runeConfig = {
  app: {
    title: "NOOB INCREMENTAL",
    subtitle: "Rune Calculator",
    chips: ["Runes", "Luck", "Idle"],
    version: "1.0.0",
  },

  defaults: {
    runeBulk: "500.2b",
    runeLuck: "200m",
    cooldownSpeed: "0.05",
    bulkPotion: true,
    luckPotion: true,
    speedPotion: true,
    theme: "dark",
    mode: "category",
  },

  suffixes: [
    { val: 1e3, sym: "k" },
    { val: 1e6, sym: "m" },
    { val: 1e9, sym: "b" },
    { val: 1e12, sym: "t" },
    { val: 1e15, sym: "qd" },
    { val: 1e18, sym: "qn" },
    { val: 1e21, sym: "sx" },
    { val: 1e24, sym: "sp" },
    { val: 1e27, sym: "oc" },
    { val: 1e30, sym: "no" },
    { val: 1e33, sym: "de" },
    { val: 1e36, sym: "ude" },
    { val: 1e39, sym: "dde" },
    { val: 1e42, sym: "tde" },
    { val: 1e45, sym: "qdde" },
    { val: 1e48, sym: "qnde" },
    { val: 1e51, sym: "sxde" },
    { val: 1e54, sym: "spde" },
    { val: 1e57, sym: "ocde" },
    { val: 1e60, sym: "node" },
    { val: 1e63, sym: "vgde" },
  ],

  categoryOrder: [
    "Basic Rune",
    "Super Runes",
    "Advanced Runes",
    "Hacker Runes"
  ],

  specialOrder: [
    "Cosmic Prism",
  ],

  categories: {
    "Basic Rune": {
      label: "Basic Rune",
      color: "#0ea5b7",
      icon: "cube",
    },
    "Super Runes": {
      label: "Super Runes",
      color: "#fb923c",
      icon: "fire",
    },
    "Advanced Runes": {
      label: "Advanced Runes",
      color: "#a855f7",
      icon: "atom",
    },
    "Cosmic Prism": {
      label: "Cosmic Prism",
      color: "#22d3ee",
      icon: "gem",
    },
    "Hacker Runes": {
    label: "Hacker Runes",
    color: "#22c55e",
    icon: "terminal",
    },
  },

  runes: [
    { name: "Rookie", type: "Basic Rune", cls: "Basic", raw: "1.25", level: 500, color: "#64748b", premium: false },
    { name: "Learner", type: "Basic Rune", cls: "Basic", raw: "6.67", level: 400, color: "#16a34a", premium: false },
    { name: "Trained", type: "Basic Rune", cls: "Basic", raw: "33.29", level: 300, color: "#0891b2", premium: false },
    { name: "Skilled", type: "Basic Rune", cls: "Basic", raw: "200", level: 200, color: "#9333ea", premium: false },
    { name: "Expert", type: "Basic Rune", cls: "Basic", raw: "50k", level: 150, color: "#ca8a04", premium: false },
    { name: "Master", type: "Basic Rune", cls: "Basic", raw: "1M", level: 115, color: "#dc2626", premium: false },
    { name: "Grandmaster", type: "Basic Rune", cls: "Basic", raw: "40M", level: 95, color: "#ea580c", premium: true },
    { name: "Celestial", type: "Basic Rune", cls: "Basic", raw: "625B", level: 75, color: "#c026d3", premium: true },
    { name: "Immortal", type: "Basic Rune", cls: "Basic", raw: "769Sp", level: 50, color: "#0d9488", premium: true },
    { name: "Shadow", type: "Basic Rune", cls: "Noobinial", raw: "10Sx", level: 5, color: "#6d28d9", premium: true },
    { name: "Phantom", type: "Basic Rune", cls: "Noobinial", raw: "10Oc", level: 20, color: "#a21caf", premium: true },
    { name: "Atomic", type: "Basic Rune", cls: "Noobinial", raw: "2Qnde", level: 9999, color: "#00ffe1", premium: true },

    { name: "Initiate", type: "Super Runes", cls: "Basic", raw: "1.11", level: 1500, color: "#16a34a", premium: false },
    { name: "Adept", type: "Super Runes", cls: "Basic", raw: "13.3", level: 1500, color: "#ca8a04", premium: false },
    { name: "Veteran", type: "Super Runes", cls: "Basic", raw: "50", level: 1500, color: "#7c3aed", premium: false },
    { name: "Elite", type: "Super Runes", cls: "Basic", raw: "5k", level: 250, color: "#c2410c", premium: false },
    { name: "Champion", type: "Super Runes", cls: "Basic", raw: "200k", level: 175, color: "#65a30d", premium: false },
    { name: "Ascended", type: "Super Runes", cls: "Basic", raw: "2M", level: 125, color: "#0d9488", premium: false },
    { name: "Transcendent", type: "Super Runes", cls: "Basic", raw: "50M", level: 100, color: "#be123c", premium: false },
    { name: "Universal", type: "Super Runes", cls: "Basic", raw: "20Qn", level: 75, color: "#9333ea", premium: false },
    { name: "Omnipotent", type: "Super Runes", cls: "Basic", raw: "17.5Oc", level: 50, color: "#65a30d", premium: true },
    { name: "Eclipse", type: "Super Runes", cls: "Noobinial", raw: "15Sp", level: 10, color: "#c026d3", premium: true },
    { name: "Void", type: "Super Runes", cls: "Noobinial", raw: "10No", level: 25, color: "#2563eb", premium: true },
    { name: "Primordial", type: "Super Runes", cls: "Noobinial", raw: "25UDe", level: 25, color: "#15803d", premium: true },

    { name: "Little", type: "Advanced Runes", cls: "Basic", raw: "1.01", level: 600, color: "#9333ea", premium: false },
    { name: "Lesser", type: "Advanced Runes", cls: "Basic", raw: "100k", level: 500, color: "#2563eb", premium: false },
    { name: "Standard", type: "Advanced Runes", cls: "Basic", raw: "1M", level: 400, color: "#475569", premium: false },
    { name: "Greater", type: "Advanced Runes", cls: "Basic", raw: "50M", level: 300, color: "#e11d48", premium: false },
    { name: "Superior", type: "Advanced Runes", cls: "Basic", raw: "200M", level: 200, color: "#16a34a", premium: false },
    { name: "Prime", type: "Advanced Runes", cls: "Basic", raw: "100B", level: 150, color: "#4f46e5", premium: false },
    { name: "Apex", type: "Advanced Runes", cls: "Basic", raw: "1T", level: 125, color: "#991b1b", premium: false },
    { name: "Ethereal", type: "Advanced Runes", cls: "Basic", raw: "50T", level: 100, color: "#0891b2", premium: false },
    { name: "Divine", type: "Advanced Runes", cls: "Basic", raw: "200Qd", level: 75, color: "#64748b", premium: false },
    { name: "Infinite", type: "Advanced Runes", cls: "Basic", raw: "17.5Oc", level: 50, color: "#ea580c", premium: true },
    { name: "Abyss", type: "Advanced Runes", cls: "Noobinial", raw: "100Sp", level: 15, color: "#b91c1c", premium: true },
    { name: "Enigma", type: "Advanced Runes", cls: "Noobinial", raw: "10De", level: 30, color: "#65a30d", premium: true },
    { name: "Seraphim's Tear", type: "Advanced Runes", cls: "Noobinial", raw: "400TDe", level: 6, color: "#6366f1", premium: true },

    { name: "Lucent", type: "Cosmic Prism", cls: "Basic", raw: "2.5", level: 85, color: "#3b82f6", premium: false },
    { name: "Chroma", type: "Cosmic Prism", cls: "Basic", raw: "4", level: 157, color: "#dc2626", premium: false },
    { name: "Fractal", type: "Cosmic Prism", cls: "Basic", raw: "20", level: 213, color: "#ca8a04", premium: false },
    { name: "Refraction", type: "Cosmic Prism", cls: "Basic", raw: "100", level: 253, color: "#991b1b", premium: false },
    { name: "Tessellation", type: "Cosmic Prism", cls: "Basic", raw: "200", level: 399, color: "#a16207", premium: false },
    { name: "Hyperlight", type: "Cosmic Prism", cls: "Basic", raw: "333", level: 678, color: "#16a34a", premium: false },
    { name: "PrismGod", type: "Cosmic Prism", cls: "Basic", raw: "1k", level: 926, color: "#2563eb", premium: true },
    { name: "Voidglass", type: "Cosmic Prism", cls: "Basic", raw: "1M", level: 75, color: "#a21caf", premium: true },
    { name: "Godshard", type: "Cosmic Prism", cls: "Noobinial", raw: "100M", level: 25, color: "#d97706", premium: true },
    { name: "Ultimate Shard", type: "Cosmic Prism", cls: "Noobinial", raw: "667B", level: 25, color: "#4206d9", premium: true },

    { name: "Script", type: "Hacker Runes", cls: "Basic", raw: "1.01", level: 0, color: "#22c55e", premium: false },
    { name: "Protocol", type: "Hacker Runes", cls: "Basic", raw: "4.29", level: 0, color: "#16a34a", premium: false },
    { name: "Cipher", type: "Hacker Runes", cls: "Basic", raw: "3.43M", level: 0, color: "#06b6d4", premium: false },
    { name: "Exploit", type: "Hacker Runes", cls: "Basic", raw: "543B", level: 0, color: "#3b82f6", premium: false },
    { name: "Kernel", type: "Hacker Runes", cls: "Basic", raw: "543T", level: 0, color: "#8b5cf6", premium: false },
    { name: "Root", type: "Hacker Runes", cls: "Basic", raw: "53Qd", level: 0, color: "#ec4899", premium: false },
    { name: "Backdoor", type: "Hacker Runes", cls: "Basic", raw: "43Qn", level: 0, color: "#f97316", premium: false },
    { name: "Rootkit", type: "Hacker Runes", cls: "Noobinial", raw: "10Oc", level: 0, color: "#ef4444", premium: true },
    { name: "Masterkey", type: "Hacker Runes", cls: "Noobinial", raw: "200Oc", level: 0, color: "#10b981", premium: true },
    { name: "Stuxnet", type: "Hacker Runes", cls: "Noobinial", raw: "105No", level: 0, color: "#a010b9", premium: true },

  ],
} as const;
